Fix, Cleanup

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -45,23 +45,23 @@ ynh_script_progression --message="Ensuring downward compatibility..." --weight=1
 
 # Fix is_public as a boolean value
 if [ "$is_public" = "Yes" ]; then
-	ynh_app_setting_set --app=$app --key=is_public --value=1
-	is_public=1
+    ynh_app_setting_set --app=$app --key=is_public --value=1
+    is_public=1
 elif [ "$is_public" = "No" ]; then
-	ynh_app_setting_set --app=$app --key=is_public --value=0
-	is_public=0
+    ynh_app_setting_set --app=$app --key=is_public --value=0
+    is_public=0
 fi
 
 # If db_name doesn't exist, create it
 if [ -z "$db_name" ]; then
-	db_name=$(ynh_sanitize_dbid --db_name=$app)
-	ynh_app_setting_set --app=$app --key=db_name --value=$db_name
+    db_name=$(ynh_sanitize_dbid --db_name=$app)
+    ynh_app_setting_set --app=$app --key=db_name --value=$db_name
 fi
 
 # If final_path doesn't exist, create it
 if [ -z "$final_path" ]; then
-	final_path=/opt/yunohost/$app
-	ynh_app_setting_set --app=$app --key=final_path --value=$final_path
+    final_path=/opt/yunohost/$app
+    ynh_app_setting_set --app=$app --key=final_path --value=$final_path
 fi
 
 #=================================================
@@ -72,8 +72,8 @@ ynh_script_progression --message="Backing up the app before upgrading (may take 
 # Backup the current version of the app
 ynh_backup_before_upgrade
 ynh_clean_setup () {
-	# restore it if the upgrade fails
-	ynh_restore_upgradebackup
+    # restore it if the upgrade fails
+    ynh_restore_upgradebackup
 }
 # Exit if an error occurs during the execution of the script
 ynh_abort_if_errors
@@ -93,21 +93,21 @@ ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app
 
 if [ "$upgrade_type" == "UPGRADE_APP" ]
 then
-	ynh_script_progression --message="Upgrading source files..." --weight=1
+    ynh_script_progression --message="Upgrading source files..." --weight=1
 
-	# Backup files to keep
-	tmpdir=$(mktemp -d)
-	if [ -d $final_path/live/log ] ; then
-		cp -Rp $final_path/live/log $tmpdir
-	fi
-	# Remove destination directory
-	ynh_secure_remove --file=$final_path
-	# Download, check integrity, uncompress and patch the source from app.src
-	mkdir -p $final_path
-	ynh_setup_source --dest_dir="$final_path/live"
-	if [ -d $tmpdir/log ] ; then
-		cp -Rp $tmpdir/log $final_path/live
-	fi
+    # Backup files to keep
+    tmpdir=$(mktemp -d)
+    if [ -d $final_path/live/log ] ; then
+        cp -Rp $final_path/live/log $tmpdir
+    fi
+    # Remove destination directory
+    ynh_secure_remove --file=$final_path
+    # Download, check integrity, uncompress and patch the source from app.src
+    mkdir -p $final_path
+    ynh_setup_source --dest_dir="$final_path/live"
+    if [ -d $tmpdir/log ] ; then
+        cp -Rp $tmpdir/log $final_path/live
+    fi
 fi
 
 #=================================================
@@ -129,7 +129,7 @@ ynh_install_app_dependencies $pkg_dependencies
 #=================================================
 # INSTALL RUBY
 #=================================================
-ynh_script_progression --message="Installing Ruby...( This may take a while... )" --weight=100	#331
+ynh_script_progression --message="Installing Ruby...( This may take a while... )" --weight=100 #331
 
 ynh_install_ruby --ruby_version=$RUBY_VERSION
 /opt/rbenv/versions/$RUBY_VERSION/bin/gem update --system --no-document
@@ -151,34 +151,35 @@ ynh_system_user_create --username=$app --home_dir=$final_path
 config_file="$final_path/live/.env"
 if [ "$upgrade_type" == "UPGRADE_APP" ]
 then
-	ynh_script_progression --message="Modifying a config file..."  --weight=2
+    ynh_script_progression --message="Modifying a config file..."  --weight=2
 
-	cp -f ../conf/env.sample $config_file
-	ynh_replace_string --match_string="EXPOSED_PORT=3000" --replace_string="EXPOSED_PORT=$port" --target_file="$config_file"
-	secret_key=$(ynh_string_random --length=48 | base64)
-	ynh_replace_string --match_string="SECRET_KEY_BASE=changeme123" --replace_string="SECRET_KEY_BASE=$secret_key" --target_file="$config_file"
-	pseudo_key=$(ynh_string_random --length=48 | base64)
-	ynh_replace_string --match_string="PSEUDO_KEY_PARAMS_KEY=changeme456" --replace_string="PSEUDO_KEY_PARAMS_KEY=$pseudo_key" --target_file="$config_file"
-	ynh_replace_string --match_string="RAILS_ENV=development" --replace_string="RAILS_ENV=production" --target_file="$config_file"
-	ynh_replace_string --match_string="DB_DATABASE=standard_notes_db" --replace_string="DB_DATABASE=$db_name" --target_file="$config_file"
-	ynh_replace_string --match_string="DB_USERNAME=std_notes_user" --replace_string="DB_USERNAME=$db_user" --target_file="$config_file"
-	ynh_replace_string --match_string="DB_PASSWORD=changeme123" --replace_string="DB_PASSWORD=$db_pwd" --target_file="$config_file"
+    cp -f ../conf/env.sample $config_file
+    ynh_replace_string --match_string="EXPOSED_PORT=3000" --replace_string="EXPOSED_PORT=$port" --target_file="$config_file"
+    secret_key=$(ynh_string_random --length=48 | base64)
+    ynh_replace_string --match_string="SECRET_KEY_BASE=changeme123" --replace_string="SECRET_KEY_BASE=$secret_key" --target_file="$config_file"
+    pseudo_key=$(ynh_string_random --length=48 | base64)
+    ynh_replace_string --match_string="PSEUDO_KEY_PARAMS_KEY=changeme456" --replace_string="PSEUDO_KEY_PARAMS_KEY=$pseudo_key" --target_file="$config_file"
+    ynh_replace_string --match_string="RAILS_ENV=development" --replace_string="RAILS_ENV=production" --target_file="$config_file"
+    ynh_replace_string --match_string="DB_DATABASE=standard_notes_db" --replace_string="DB_DATABASE=$db_name" --target_file="$config_file"
+    ynh_replace_string --match_string="DB_USERNAME=std_notes_user" --replace_string="DB_USERNAME=$db_user" --target_file="$config_file"
+    ynh_replace_string --match_string="DB_PASSWORD=changeme123" --replace_string="DB_PASSWORD=$db_pwd" --target_file="$config_file"
+    ynh_replace_string --match_string="RAILS_RELATIVE_URL_ROOT=/" --replace_string="RAILS_RELATIVE_URL_ROOT=$path_url" --target_file="$config_file"
 fi
 #=================================================
 # INSTALLING Standard Notes - Synicing Server 
 #=================================================
 if [ "$upgrade_type" == "UPGRADE_APP" ]
 then
-	ynh_script_progression --message="Installing Standard Notes - Synicing Server..."  --weight=93
-	
-	chown -R "$app": "$final_path"
-	
-	pushd "$final_path/live"
-		exec_as "$app" env PATH=$PATH /opt/rbenv/versions/$RUBY_VERSION/bin/bundle config set path 'vendor/bundle'
-		exec_as "$app" env PATH=$PATH /opt/rbenv/versions/$RUBY_VERSION/bin/bundle config set with 'development'
-		exec_as "$app" env PATH=$PATH /opt/rbenv/versions/$RUBY_VERSION/bin/bundle install
-		exec_as "$app" env PATH=$PATH RAILS_ENV=production /opt/rbenv/versions/$RUBY_VERSION/bin/bundle exec rails db:create db:migrate
-	popd
+    ynh_script_progression --message="Installing Standard Notes - Synicing Server..."  --weight=93
+
+    chown -R "$app": "$final_path"
+
+    pushd "$final_path/live"
+        exec_as "$app" env PATH=$PATH /opt/rbenv/versions/$RUBY_VERSION/bin/bundle config set path 'vendor/bundle'
+        exec_as "$app" env PATH=$PATH /opt/rbenv/versions/$RUBY_VERSION/bin/bundle config set with 'development'
+        exec_as "$app" env PATH=$PATH /opt/rbenv/versions/$RUBY_VERSION/bin/bundle install
+        exec_as "$app" env PATH=$PATH RAILS_ENV=production /opt/rbenv/versions/$RUBY_VERSION/bin/bundle exec rails db:create db:migrate --quiet
+    popd
 fi
 
 #=================================================
@@ -187,9 +188,10 @@ fi
 ynh_script_progression --message="Upgrading systemd configuration..." --weight=1
 
 # Create a dedicated systemd config
-ynh_replace_string --match_string="__PORT__" --replace_string="$port" --target_file="../conf/systemd.service"
-ynh_replace_string --match_string="__RUBY_VERSION__" --replace_string="$RUBY_VERSION" --target_file="../conf/systemd.service"
-ynh_add_systemd_config --service="$app" --template="systemd.service"
+ynh_add_systemd_config --others_var="\
+    port \
+    RUBY_VERSION \
+"
 
 #=================================================
 # STORE THE CONFIG FILE CHECKSUM
@@ -209,13 +211,13 @@ ynh_store_file_checksum --file="/etc/nginx/conf.d/$domain.d/$app.conf"
 # Set permissions to app files
 chown -R root: $final_path
 chown $app: $final_path
-mkdir -p $final_path/live/log
-chown -R $app: $final_path/live/log/
-mkdir -p $final_path/live/tmp
-chown -R $app: $final_path/live/tmp/
+mkdir -p "$final_path/live/log"
+chown -R $app: "$final_path/live/log/"
+mkdir -p "$final_path/live/tmp"
+chown -R $app: "$final_path/live/tmp/"
 
-mkdir -p /var/log/$app
-chown -R $app: /var/log/$app
+mkdir -p "/var/log/$app"
+chown -R $app: "/var/log/$app"
 
 #=================================================
 # SETUP LOGROTATE
@@ -247,10 +249,10 @@ ynh_script_progression --message="Upgrading SSOwat configuration..." --weight=1
 # Make app public if necessary or protect it
 if [ $is_public -eq 1 ]
 then
-	# Create the visitors permission if needed
-	if ! ynh_permission_exists --permission "main"; then
-		ynh_permission_create --permission "main" --allowed "visitors"
-	fi
+    # Create the visitors permission if needed
+    if ! ynh_permission_exists --permission "main"; then
+        ynh_permission_create --permission "main" --allowed "visitors"
+    fi
 fi
 
 #=================================================
@@ -260,7 +262,6 @@ ynh_script_progression --message="Starting a systemd service..." --weight=1
 
 # Start a systemd service
 ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"
-# Wait 10 secends tor server to start
 sleep 10
 
 #=================================================
